# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Museum
email: hugo.marti@protonmail.com
description: > # this means to ignore newlines until "baseurl:"
  Collection de mes découvertes tech
  
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://h-marti.github.io/" # the base hostname & protocol for your site

#sidebar
# default-image: webjeda-logo-big.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer

built-by: h-marti

copyright:
   name: h-marti
   link: 'https://h-marti.github.io/'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
# analytics: UA-83979019-1

# Comments
# disqus: yes
# disqus-shortname: webjeda-demo

#social
linkedin: https://fr.linkedin.com/in/h-marti
twitter: https://twitter.com/Martinou1985
github: https://github.com/h-marti
email: hugo.marti@protonmail.com

# Sass style
sass:
  style: compressed

# Ruby Gems
plugins: 
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji
  - rouge
  - jekyll-sitemap

